apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  app.py: |
    from flask import Flask, jsonify

    app = Flask(__name__)

    @app.route('/ping', methods=['GET'])
    def api():
        return jsonify({"message": "Hello from Greeter API!"})

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000)
